branches:
  only:
    - master
    - develop
    - /^hotfix.*$/
    - /^feature.*$/

notifications:
  email:
    on_success: change
    on_failure: always

env:
  - FASTLANE_SKIP_UPDATE_CHECK=true

language: swift

stages:
  - Tests
  - Compatibility

jobs:
  include:
    - stage: Tests
      os: osx
      osx_image: xcode11
      name: Tests
      script: 
        - fastlane ios tests
        - fastlane ios compatibilityTests
